[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "cc_hardware_utils"
version = "0.0"
authors = ["Camera Culture <a2cc@media.mit.edu>"]
description = "CC Hardware Utils"
readme = "README.md"
packages = [
    { include = "cc_hardware" }
]

[tool.poetry.dependencies]
python = ">=3.12"
tqdm = "^4.66.5"
scipy = "^1.14.1"
imageio = "^2.35.1"
SciencePlots = "^2.1.1"
seaborn = "^0.13.2"
matplotlib = "^3.9.2"
psutil = "^6.1.0"
hydra-config = "^0.0.15"
torch = "^2.7.1"
